### PR TITLE
Fix name collision with lxml's setupinfo.py

### PR DESCRIPTION
**Pull request by sindrig**
When installing (ubuntu and arch, python 3.6.2 and python 3.5.x), lxml installation fails because it tries to import its own `setupinfo.py`, but gets python-xmlsec's `setupinfo.py`. Rename the module to make sure we don't get another name collision.

### CODE REVIEW

**Comment by bgaifullin** [comment]
How does it happen. setupinfo is local file inside of package. why lxml tries to import file from xmlsec?

**Comment by bgaifullin** [comment]
Can you describe case step by step ?

**Comment by sindrig** [comment]
Not quite sure, but I suspect it's because you've imported `setuptools` in `setup.py` and it is in `sys.modules`. When lxml's `setup.py` imports `setuptools` it first searches in `sys.modules`.

**Comment by bgaifullin** [comment]
I got it, thank you.

**Pull request merged**
