### PR TITLE
Rewrote whole module on pure C

### PR DESCRIPTION
**Pull request by bgaifullin**
Keep backward compatibility of API.
Removed submodules "ds", "key", "enc".
the namespaces from constants was moved to main package,
constants contains only flat list of xmlsec constants.

### CODE REVIEW

**Comment by bgaifullin** [comment]
the python3-saml tests passed.
There is one known issue. the module does not work with python3.5 on ubuntu:precise, 
since there is problems with memory allocation in version of lxml2 which is default for precise.
Other versions of python: python3.4 or python2.7 works on precise.

On trusty and xenial it works well for python2.7, python3.4 and python3.5
I also tested with macos on python2.7, python3.5 and python3.6, there is no problem.

I switched travise-ci to use trusty version instead of precise.

**Comment by bgaifullin** [comment]
@mehcode,  could you please review.

**Comment by mehcode** [comment]
Super awesome @bgaifullin !

**Comment by mehcode** [comment]
Released (and added you as an owner in PyPi)

**Comment by bgaifullin** [comment]
@mehcode thanks

**Pull request merged**
