### PR TITLE
support encryption, transformation

### PR DESCRIPTION
**Pull request by bgaifullin**
- unify exceptions
- support encryption, transformation
- unify error-handling

### CODE REVIEW

**Comment by pitbulk** [comment]
@mehcode, I also need this PR merged.

**Comment by mehcode** [comment]
@bgaifullin Thanks for this awesome PR. Looking at it right now.

**Comment by bgaifullin** [comment]
There was problem with build on travis. It does not cause of changes in code. I will investigate this problem.

**Comment by mehcode** [comment]
@bgaifullin I can investigate the test crash on travis, that's fine. Could you add a test specific to encryption?

**Comment by bgaifullin** [comment]
Of course. I am going to add.

**Comment by mehcode** [comment]
@bgaifullin FYI I fixed the travis build on master

**Comment by bgaifullin** [comment]
I have added tests.

**Comment by bgaifullin** [comment]
Please, let me know if any other changes is required.

**Comment by mehcode** [comment]
This looks great @bgaifullin; awesome work

**Pull request merged**
